### ISSUE TITLE
Attached images not shown

### ISSUE THREAD

**Issue by cholmcc** [AliceO2Group/Bookkeeping#809]
See f.ex. https://ali-bookkeeping.cern.ch/api/attachments/1505?page=log-detail&id=38173.  When clicking the attached images, the images simply fail to load.   If I say "Open in new tab" (right-click context menu), then the images does show up.  However, if I try to download the images from the new tab, then I get a network error.  Perhaps a problem is that the files how no "extension" - i.e., the file name is `1506` not `1506.png`.    This makes it hard to communicate things since image attachements are not really useful.  BTW, is there a way to include the image inline in the log entry?  The url of the uploaded images gets all mangled so it is impossible to predict the correct URL.

**Comment by graduta** [comment]
Hi @cholmcc 

Thank you for the feedback!
For the FLP project (Bookkeeping included), we use JIRA for tracking issues and new features requests. In this case, the bug has been raised by another user and it is due to have a fix released this week, with a deployment at P2 planned for next week: https://alice.its.cern.ch/jira/browse/O2B-774

For future issues, it would be great if you could raise it directly on our Jira board.
Thank you!
